#!/usr/bin/env bash
set -euo pipefail

: "${NEUROLENS_ROOT:=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
: "${OUT_ROOT:=${NEUROLENS_ROOT}/outputs}"
: "${INTERACTION_ROOT:=${OUT_ROOT}/interaction_eval}"
: "${ANSWERS_JSON:?Set ANSWERS_JSON to the json file generated by generate_neurolens_interaction_answers.py.}"

python "${NEUROLENS_ROOT}/src/evaluate_neurolens_interaction_bertscore.py" \
  --answers_json="${ANSWERS_JSON}" \
  --out_dir="${INTERACTION_ROOT}"
